### ISSUE TITLE
【要望・提案】issue前後のbefore afterが欲しい

### ISSUE THREAD

**Issue by Leaf47** [ookam/yaminabe#10]
要望・提案の種類（一致するものを残して他は消して下さい）
- デザイン
- 機能
- その他

## 私はこれを要望・提案します！
- こんなissueでこんな風に変わったよ！っていうのがひと目でわかるようなコンテンツが欲しいです。

## サイト上でのURLやスクショ
- 

## 補足
- こちらのissueからの派生です。
- https://github.com/ookam/yaminabe/issues/4

**Comment by Leaf47** [comment]
実現できるかどうかはわからないのですけど、例えばissueページにbefore afterのスクショを置いといて、ページの該当箇所に小さなリンク(wikiのダガーみたいな)を設置してissueページに飛ばす・・・とか？

そしたら「ここはこんなissueがあってこんな風に変わったんだ！」ってのがわかりやすいかも、なんて思いました。

**Comment by ookam** [comment]
issueに前後のスクショを貼るのは、僕以外の人がめんどくさくてやってくれない可能性があるのでログをまとめるくらいしかできないかもです！

俯瞰できたら絶対面白いけど運用コスト的に厳しそう、、、うむむ、、、

**Comment by dowdiness** [comment]
Vercelを使えばプルリクエストやブランチへのプッシュが来るたびに自動でプレビュー用のサイトを作ってくれるので楽に前後の変化を比較出来ると思うのですが、どうでしょうか？
https://vercel.com/docs/platform/deployments#preview

それかreg-suitみたいなVisual Regression Testing toolを使うのも良いと思います。
https://github.com/reg-viz/reg-suit

**Comment by mikkame** [comment]
fastlyでもデプロイプレビュー出来ますね。
ただ、prに紐ずくと思うのでactionsでスクショ撮った方がいいかも？

**Comment by mikkame** [comment]
> issueに前後のスクショを貼るのは、僕以外の人がめんどくさくてやってくれない可能性があるのでログをまとめるくらいしかできないかもです！
> 
> 俯瞰できたら絶対面白いけど運用コスト的に厳しそう、、、うむむ、、、

これについては過去ログから生成する！ってのをやった事あります。結構手間。、

**Comment by ookam** [comment]
コンセプトが同じ仕組みで他のサイトも簡単に真似できる〜なので、githubだけで完結したいです（わがままでごめんなさい！！！！）

そうなると、github actionでスクショを撮って自動で貼るのは悪くなさそうな雰囲気ありますね！トップページだけ〜とかならそれで運用できそう（後ほどまとめて記録ファイルを書くのは手動でやるとして）

ただ問題はgithub pageって反映に時間がかかるのでdeploy直後などに撮った場合旧バージョンのスクショになってしまうんですよね

ここ難しい、、、

**Comment by mikkame** [comment]
反映が遅い件は

distを起点にpythonのsimpleサーバーとかphpのビルトインで起動してそれわスクショするといいですよ

**Comment by ookam** [comment]
あーなるほど、たしかにその方法だったら全自動で行けそうな気がしますね！！！（僕が作れるとは言ってない

**Comment by Michin0suke** [comment]
スクショじゃなくて魚拓というのはどうですかー？
Githubで完結してないですが、一つ手段としてあってもいいかなと思います！

#### 手順
1. Github Actionsで[Internet ArchiveのAPI](https://archive.org/help/wayback_api.php)を叩く
2. 帰ってきたタイムスタンプと世代を紐付けたjsonファイルを生成（タイムスタンプとURLがあれば魚拓にアクセスできるので）
3. サイトではajaxで生成されたjsonを読み込む

#### メリット
- 世代が進んでも画像ファイルでリポジトリが重くならない
- スクショと違ってJSが動く

#### デメリット
- 一目で分からない
- CIが長くなる
- beforeしか見れない
- Internet Archiveの仕様上、30分に１度しか魚拓が取れないので、その間ビルドを通せない...

書いてて思ったんですが現実的じゃないですね笑 ごめんなさい...
APIだけ叩いておくのはアリなんじゃないでしょうか！

**Comment by mikkame** [comment]
> あーなるほど、たしかにその方法だったら全自動で行けそうな気がしますね！！！（僕が作れるとは言ってない

作るのでアサインください！

**Comment by ookam** [comment]
ありがとうございます！！！！！！感謝！！！！！！！！

**Comment by mikkame** [comment]
とりあえずスクショスクリプトまで作りました。
あとはどこに保存するか検討してそこに収めましょう！

保存先
- どっかの特別なブランチ（容量大きくなりすぎるとLFSしないといけない）
- 別リポジトリ
- ActionsのArtifact（いつまで保存されるかわからん）

**Comment by ookam** [comment]
仕組みとして誰でも特に負担なくというのが理想なので、どれが一番良いんでしょうね……

**Comment by mikkame** [comment]
とりあえず別ブランチにして容量パンクしそうだったらブランチを消してその時考えるでどうでしょう

**Comment by ookam** [comment]
将来的に放置で運営出来るのが良いので、詳しい人間以外は追えない（＆いつパンクするかわからない時限爆弾になりやすい）挙動は微妙な気がするんですよね

例えばgithubのissueに一回画像を添付して投稿して、そのURLを引っ張ってくるとかなら良さそうなんですけどそういうメンテフリーな方法無いですかね？

**Comment by mikkame** [comment]
若干闇手法ですね→issue
https://docs.github.com/ja/github/administering-a-repository/about-releases
リリースに打ち込むのが容量的にはよさそうです。閲覧性は下がりますが。

> リリースに含まれる各ファイルは、2 GB以下でなければなりません。 リリースの合計サイズにも帯域幅の使用量にも制限はありません。

**Comment by ookam** [comment]
そうなるとスクショ取るのを諦めるのも若干ありですよね（合ったほうが面白いけど）
シンプルなほうがいいでしょうし

**Comment by mikkame** [comment]
成長過程を見れたならーぐらいの
おまけ要素がつよいんですよねぇ。
なくても成立するってのはあります

**Comment by mikkame** [comment]
issueかprがactions蹴れるのでそこから差し込めるかを考えます！

**Comment by mikkame** [comment]
ちょっと整理。Issueのタイトル的には雑にみれればOKでセセリさん的には俯瞰したデータにしたい。
後者が主題でOKですか？

**Comment by ookam** [comment]
んんんん？理解できてない感じです！別の表現でもう一回きいてもいいですか！！！すいません！！！！

**Comment by mikkame** [comment]
目指す所の再確認をしたいです！

**Comment by Leaf47** [comment]
ボクが当初issueをあげた理由としてはタイトル通り「issueをあげる前と解決後でどのように変わったのか？」がわかるようにしたいというものです。
誰でも参加できる・参加してほしいってコンセプトから、**GitHubとかプログラムとかがよくわからなくても理解できるもの**がほしいと思って「スクショ貼ればわかりやすいんじゃね？」と一例(案)をあげました。
なのでmikkameさんの質問はどちらも正解なんだと思います。

雑な表現でもこんな風に変わったんだってのがわかればいいと思いますし、俯瞰して流れが見れるようになればさらにいいものになってるんじゃないかと思います。

さらに言ってしまうと、↑で出てる魚拓のように、スクショにこだわる必要もないのかな？と思います。

ボクの思いはこんなところです><
