### ISSUE TITLE
【不具合】CIが一生終わらない

### ISSUE THREAD

**Issue by Miyoshi-Ryota** [ookam/yaminabe#12]
## ここが不具合だと思いました！

不具合の種類（一致するものを残して他は消して下さい）
- デザインが崩れている
- サイトにアクセス出来ない、エラーが出る
- リンクが間違っている
- 文字の間違い、誤字がある
- その他

動作環境は？（一致するものを残して他は消して下さい）
- PC
- タブレット
- スマートフォン
- ゲーム機

## これを確認できるURL / スクショ
- 

## こうなってほしい！
- 

## 補足
-

**Comment by Miyoshi-Ryota** [comment]
間違えて内容書く前に送ってしまいました。いま編集中です。

**Comment by ookam** [comment]
原因さぐります！！

**Comment by Miyoshi-Ryota** [comment]
いま編集中ですが、yarn buildが一生終わらないっぽいです。CIが無事回ってたときのコミットでは問題なく終わっていたんですが、CIが回らないコミットでは、yarn buildが一生終わらないっぽいです。取り急ぎ。

**Comment by ookam** [comment]
直しました！４時間くらい周りっぱでした……つっこみありがとうございます！！！！感謝！！！！

**Comment by Miyoshi-Ryota** [comment]
早い！中途半端なIssueですが、もう詳細を書く必要がないので今のままにしておきますね！
