### ISSUE TITLE
【要望・提案】コントリビューターの一覧を作成する

### ISSUE THREAD

**Issue by Yuta-KTD** [ookam/yaminabe#13]
要望・提案の種類（一致するものを残して他は消して下さい）
- 機能
- 開発チーム（ここ）

## 私はこれを要望・提案します！
- コントリビューターの一覧を作ると開発者のモチベーションにも繋がりそうです。（現状作る優先順位は低そうですが...）
- おめシスさんのHPにも同じ機能がありますが、オープンソース開発においてあったら嬉しい機能だと思い提案しました。
- イメージはサイト内か、もしくはリポジトリのREADME.mdファイル内に記載する感じです。

## サイト上でのURLやスクショ
- [おめシスのリポジトリでの同問題のissue](https://github.com/omegasisters/homepage/issues/256)

## 補足
- 人生初issueなので間違っている点、よろしくない点などありましたらがっつり指摘してください！

**Comment by ookam** [comment]
issueありがとうございます🎉🎉🎉🎉

確かにあると良さそうですね！！！
jsでREST APIを叩くのでlimitを超えないかちょっと悩ましいですね
deploy時にキャッシュする戦略もありかも……誰か仕様提案あったらお願いします！！無ければ僕の方で考えます！！！

**Comment by ookam** [comment]
https://ookam.github.io/yaminabe/contributors/

![image](https://user-images.githubusercontent.com/29398170/107946330-3c477d00-6fd4-11eb-9d61-5371a934da92.png)

実装しました！！！デザインに関しては「このサイトっぽくしよう」みたいなアイデアが誰かあったらまたissue下さい！！！
