### ISSUE TITLE
【要望・提案】GitHubリポジトリへのリンクを作成する

### ISSUE THREAD

**Issue by Yuta-KTD** [ookam/yaminabe#14]
要望・提案の種類（一致するものを残して他は消して下さい）
- 機能

## 私はこれを要望・提案します！
- リポジトリへのリンクを作成する
- 現状HPにIssueやプルリクへの導線が無いように見受けられたので

## サイト上でのURLやスクショ
- 

## 補足
-

**Comment by ookam** [comment]
提案ありがとうございます！🎉🎉

#15 で解決しました！
