### ISSUE TITLE
【要望・提案】タイトル虹色にしてスクロールさせてください

### ISSUE THREAD

**Issue by hayashi-884** [ookam/yaminabe#19]
要望・提案の種類（一致するものを残して他は消して下さい）
- デザイン
90年代風

## 私はこれを要望・提案します！
- 

## サイト上でのURLやスクショ
- 

## 補足
-

**Comment by ookam** [comment]
！！！！！？！！！！！？！！！！！！？？？？？？？？？？？

やってみます！！！！横ですか？縦ですか？スロット系ですか？

**Comment by hayashi-884** [comment]
縦にﾋﾞｬｰｰｰｰっと流してください

**Comment by ookam** [comment]
りょ、りょうかいです
イメージわかないですがとりあえずやってみます！！！！！！

**Comment by hayashi-884** [comment]
光る虹色がいいです

**Comment by ookam** [comment]
とりあえず虹色は実現しました！🎉🎉🎉

ただスクロールの方はちょっとイメージが沸かなかったのでもう一回良さげな感じにまとめてissue下さい！！！
