### ISSUE TITLE
【要望・提案】コンテンツか少なくてもフッターはページの下部に表示されるようにする

### ISSUE THREAD

**Issue by taishikato** [ookam/yaminabe#2]
- 要望・提案の種類
  - [x] デザイン
  - [ ] 機能
  - [ ] テキスト
  - [ ] 開発チーム（ここ）
  - [ ] その他

## 私はこれを要望・提案したいです！

コンテンツか少ない場合にフッターがページ下部より上に表示されると、下に空白スペースができてしまうのを防ぎたいです。

## 補足

しょぼいのであれですが、とりあえずissue投げてみました！

**Comment by ookam** [comment]
ありがとうございます！！！やります！！！！！

**Comment by ookam** [comment]
修正しました！thanks！！！🎉🎉🎉🎉
