### ISSUE TITLE
【要望・提案】コントリビューター一覧ページを外部サービスに委託

### ISSUE THREAD

**Issue by mikkame** [ookam/yaminabe#20]
要望・提案の種類（一致するものを残して他は消して下さい）

- 機能

## 私はこれを要望・提案します！
- コントリビューター一覧を生成する件を外部サービスに委託してもいいのでは

## 補足
- 閲覧者のAPIを食うため。
- ~ページネーションとか大変そう~ 杞憂だった

![https://contrib.rocks/image?repo=ookam/yaminabe](https://contrib.rocks/image?repo=ookam/yaminabe)

こんな感じのやつです。

https://contrib.rocks/image?repo=ookam/yaminabe

**Comment by ookam** [comment]
登録とかなさそうならめっちゃ楽そうで良いですね！！　LGTM

これを使う場合は、それぞれのコミット数がでないのでそれをしたくなったらjsに戻す形にしましょうか！！

**Comment by mikkame** [comment]
あーすみません！
実装見ました！
毎回手動で追加するの大変だなぁと思っての提案だったので自動化出来てるなら大丈夫です！

**Comment by ookam** [comment]
了解です！
