### ISSUE TITLE
【要望・提案】main ブランチはbranch protectをつける

### ISSUE THREAD

**Issue by mikkame** [ookam/yaminabe#21]
要望・提案の種類（一致するものを残して他は消して下さい）

- 開発チーム（ここ）

## 私はこれを要望・提案します！
- せせりさんがmainに直コミしてるっぽいので

## Pros
- すべてPRフローにのる
- CIかけやすい
- PRからリリースノート作れそう
- 雑な更新がされにくくなる
- PRがマージされたのをreleaseとして管理しやすくなる→distをrelease管理すれば過去版がすべて再現可能

## Cons

- せせりさんがストレスを感じる
- 開発速度が落ちる(せせりさんがメインで実装する場合)

**Comment by ookam** [comment]
ある程度開発が固まってからでも良いですか！！（1週間後くらい）

とりあえず最初は僕の稼働が多いと思うので効率優先したいです！！
