### ISSUE TITLE
【要望・提案】多言語対応を誰でもできるようにしたい

### ISSUE THREAD

**Issue by noumi0k** [ookam/yaminabe#24]
要望・提案の種類（一致するものを残して他は消して下さい）
- その他

## 私はこれを要望・提案します！
-下記などを使って、Gitを触ったことがない、プログラミングわからないという人も、多言語対応なら参加できるような状態にしたい。
https://weblate.org/ja/

## サイト上でのURLやスクショ
- なし

## 補足
- なし

**Comment by ookam** [comment]
面白そう！！🎉
読んでみます！！

**Comment by ookam** [comment]
読みました！
有料だからしんどそう（&技術的にみんな真似できなそう）

なので採用は厳しいかもです。ただ、翻訳に誰でも参加できるというのはめっちゃ良さみありますよね

実現できないか考えてみます！

**Comment by noumi0k** [comment]
今回Githubで完結だと有料しかないですもんね・・
プログラミングできない人もissue以外で参加できる仕組み引き続き考えてみます！

**Comment by ookam** [comment]
ありがとうございます！！！！

**Comment by mikkame** [comment]
https://www.transifex.com/
これも有名ですね！

某所にHOW TOもあります
https://github.com/tokyo-metropolitan-gov/covid19/blob/development/TRANSLATION.md
