### ISSUE TITLE
【要望・提案】ワンカラムデザインにする？2カラムデザインにする？

### ISSUE THREAD

**Issue by ookam** [ookam/yaminabe#25]
要望・提案の種類（一致するものを残して他は消して下さい）
- デザイン

## 私はこれを要望・提案します！
- どちらかに決めちゃって進めたい！

## サイト上でのURLやスクショ
- 

## 補足
-

**Comment by noumi0k** [comment]
スマホ対応シンプルに行うためにワンカラム派です！

**Comment by ookam** [comment]
了解です！！！そうしましょうか！！

**Comment by ookam** [comment]
1カラム用に.containerを定義
