### ISSUE TITLE
【要望・提案】ダークモードに対応してほしい

### ISSUE THREAD

**Issue by tama-shira** [ookam/yaminabe#27]
要望・提案の種類（一致するものを残して他は消して下さい）
- デザイン
- 機能

## 私はこれを要望・提案します！
- サイト全体をダークモードに切り替える仕組みがほしい

## サイト上でのURLやスクショ
- 特になし

## 補足
- ダークモードにできるものはすべてダークモードにしたいマンです！

**Comment by ookam** [comment]
（ダークモード対応やったことない）どうやるんでしょうね！

**Comment by ookam** [comment]
https://sunday-morning.app/posts/2020-12-19-tailwind-css-dark-mode

意外と簡単そう？
ヘッダーの右上にトグルボタン置いて、クッキーにそれを保存する形で実現できそう

**Comment by ookam** [comment]
https://icons.getbootstrap.com/icons/brightness-high/

太陽のアイコン

https://icons.getbootstrap.com/icons/moon/

月のアイコン

真ん中にトグルボタンを置いて、それを押したら$("body").toggleClass("dark")するだけで最低限は実現できそう

あと、tailwind.configのdarkmodeをオンにしないと

**Comment by ookam** [comment]
tailwindのdark modeをclassにして、jsファイルで初期アクセス時（cookieが空の時）は、ブラウザのモードを使うようにすればよさそう

https://qiita.com/a01sa01to/items/7072a7e0a4d32e38ecca

js.cookieあたりもいれる必要がある

**Comment by ookam** [comment]
cdn.njkにこれを追記

<script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/js.cookie.min.js"></script>

**Comment by tama-shira** [comment]
ちょっと目を離した間にすごく調査されておられる！？
issue切っておいて自分もやったことないので、参考にさせていただきますね！笑

**Comment by ookam** [comment]
ダークモード対応も簡単！そう、、tailwindがあればね！！

みたいな感じです多分！

**Comment by ookam** [comment]
やってみます！

**Comment by ookam** [comment]
ダークモードに変更する機能自体は作りました！
ただ、ダークモードにしたい場所にそれぞれclassを振らないと行けないので全体の対応は後々になります！！！
ちょっとずつやっていきましょう！！
