### ISSUE TITLE
【不具合】htmlhintがtailwindcssの書き方に対応していない

### ISSUE THREAD

**Issue by dowdiness** [ookam/yaminabe#31]
## ここが不具合だと思いました！

不具合の種類（一致するものを残して他は消して下さい）
- その他

動作環境は？（一致するものを残して他は消して下さい）
- PC
- タブレット
- スマートフォン
- ゲーム機

## これを確認できるURL / スクショ
- tab_pc:px-8などのtailwindcssのレスポンシブ対応したクラスがある場合
![スクリーンショット 2021-02-16 2 31 40](https://user-images.githubusercontent.com/1616717/107977904-3e730100-6fff-11eb-99b2-764ce0ff6818.png)
- ない場合
![スクリーンショット 2021-02-16 2 30 40](https://user-images.githubusercontent.com/1616717/107978013-6eba9f80-6fff-11eb-84e7-28d01f56a583.png)

## こうなってほしい！
- id-class-valueのルールを無効にしてもいいかも？

## 補足
-

**Comment by ookam** [comment]
ありがとうございます！！💮💮
こちら修正してpushしました！！！🎉🎉
