### ISSUE TITLE
【要望・提案】ダークモードで見えにくくなった文字をダークモード対応したい

### ISSUE THREAD

**Issue by noumi0k** [ookam/yaminabe#35]
要望・提案の種類（一致するものを残して他は消して下さい）
- デザイン

## 私はこれを要望・提案します！
-下記プルリクの最後でも話しているように細かいダークモード対応
https://github.com/ookam/yaminabe/issues/27

## サイト上でのURLやスクショ
![スクリーンショット 2021-02-16 10 16 02](https://user-images.githubusercontent.com/5664171/108006911-fb854d80-703f-11eb-9930-04069723559f.png)

## 補足
- issueに上がってる方が漏れないので作っておきます

**Comment by ookam** [comment]
ありがとうございます！！！
こうやって上げてもらえるとめっちゃ助かります！！！！🎉🎉
