### ISSUE TITLE
【要望・提案】EASIEST_CONTRIBUTING.mdの説明に画面イメージを追加してはどうでしょうか？

### ISSUE THREAD

**Issue by dtakkiy** [ookam/yaminabe#36]
要望・提案の種類（一致するものを残して他は消して下さい）
- その他

## 私はこれを要望・提案します！
- EASIEST_CONTRIBUTING.mdの説明に画面イメージを追加してはどうでしょうか？
- 今は文章のみの説明なので、あわせて画像も表示してあげると、よりわかりやすくプルリクの敷居が下がるのではないでしょうか？

## サイト上でのURLやスクショ
- こんなイメージです。
![3](https://user-images.githubusercontent.com/24822590/108007610-c1b54680-7041-11eb-93f3-2bc728b217c7.png)
![4](https://user-images.githubusercontent.com/24822590/108007614-c4b03700-7041-11eb-9cfc-113f2df48235.png)
![5](https://user-images.githubusercontent.com/24822590/108007619-c7129100-7041-11eb-9aea-58163adb7f52.png)

## 補足
- GitHub上からは、EASIEST_CONTRIBUTING.mdに画像の追加が出来ませんでした。

**Comment by ookam** [comment]
最高です！！
ぜひお願いします！！！🎉🎉🎉

**Comment by mikkame** [comment]
サイコーです！

**Comment by Leaf47** [comment]
サイコーです！
これを参考にプルリクしました！

**Comment by dtakkiy** [comment]
うれしい！！
