### ISSUE TITLE
【要望・提案】コンテンツの配置を整理したほうがいいのでは？

### ISSUE THREAD

**Issue by Leaf47** [ookam/yaminabe#4]
- 要望・提案の種類
  - [x] デザイン
  - [ ] 機能
  - [ ] テキスト
  - [ ] 開発チーム（ここ）
  - [ ] その他

## 私はこれを要望・提案したいです！
ページタイトルや本文などコンテンツを整理したほうが可読性が上がると思います！

## 補足
白背景に黒文字だけなので、まだまださみしい・・・

**Comment by Leaf47** [comment]
こんな感じでいいのかしら・・・？

**Comment by ookam** [comment]
大丈夫です！ありがとうございます！！

どんなコンテンツがあると良いと思いますか？

**Comment by Leaf47** [comment]
このページのコンセプトが『サンプルとして「こんなのが作れるよ」ってやつ』だと思うので、こんなissueあげたらこう変わったよっていうbefore→afterみたいなのが見えたらわかりやすいのかなーと。

それをどう表現したらいいのか・・・って感じですけど(^^;;

**Comment by ookam** [comment]
なるほど……確かにそういったデータがあると良さそうですね！
何かしらの方法でbefore afterを設置したい

**Comment by Leaf47** [comment]
実現できるかどうかはわからないのですけど、例えばissueページにbefore afterのスクショを置いといて、ページの該当箇所に小さなリンク(wikiのダガーみたいな)を設置してissueページに飛ばす・・・とか？

そしたら「ここはこんなissueがあってこんな風に変わったんだ！」ってのがわかりやすいかも、なんて思いました。

**Comment by Leaf47** [comment]
てゆかタイトルと議論内容が変わってきてしまっている・・・
こんな時はどう整理したらいいのでしょう？

1. 新しいissueを作成する
2. このissueのタイトルを変更する
3. そのままでいい

**Comment by ookam** [comment]
基本的に1つのissueは1タスクだと話が整理しやすいので良いと思います！！！（つまり新しいissueを作る

**Comment by Leaf47** [comment]
了解です、新しいissue作ります！
