### ISSUE TITLE
【要望・提案】About の欄にサイトリンクを貼ってほしい。

### ISSUE THREAD

**Issue by oriverk** [ookam/yaminabe#44]
要望・提案の種類（一致するものを残して他は消して下さい）
- ドキュメント類

## 私はこれを要望・提案します！
- 現在サイトへのリンクはREADMEにのみ記載されていますが、一瞬どこだっけと探してしまうので、About欄に追記していただけるとコンマ何秒か節約できて嬉しいです。

## サイト上でのURLやスクショ
- この箇所

![Screenshot from 2021-02-16 15-55-27](https://user-images.githubusercontent.com/44029144/108028625-7ade4580-706f-11eb-86f9-09caba080897.png)

## 補足
-

**Comment by ookam** [comment]
超良い！！！
確かに貼るべきですね！やります！！
