### ISSUE TITLE
【要望・提案】文字の優先度付けをして見やすくしたい！

### ISSUE THREAD

**Issue by Kissa0330** [ookam/yaminabe#45]
要望・提案の種類（一致するものを残して他は消して下さい）
- デザイン

## 私はこれを要望・提案します！
- 「このサイトは何？」、「過去のログを見る」、「開発参加者一覧を見る」の部分のフォントサイズを大きくして、見やすいデザインにしたいです！

## 補足
- 生まれて初めてのIssueなので不備などがあればご指摘くだされば幸いです。

**Comment by ookam** [comment]
ありがとうございます！！🎉🎉

確かに分かりづらい、、、いい感じにしたいですね！
