### ISSUE TITLE
【要望・提案】サイトのタイトルを決めよう

### ISSUE THREAD

**Issue by ookam** [ookam/yaminabe#5]
要望・提案の種類（一致するものを残して他は消して下さい）
- デザイン

## 私はこれを要望・提案します！
- Headerだとダサいのでサイトのタイトルを決めて置き換えよう

## サイト上でのURLやスクショ
- 

## 補足
- サイトのタイトルは誰か考えてください

**Comment by Leaf47** [comment]
タイトル：プリオンちゃんの成長日記
サブタイトル：～プルリクエストだけでHPを作っちゃお♪～

プリオン=PUll REquest ONly から

誰かプリオンちゃんのイラストを・・・

**Comment by ookam** [comment]
可愛いですが、これは他のやつからも参照するモデルケースサイトなのでもっと硬派に行きましょう笑

**Comment by dtakkiy** [comment]
こんなタイトルはどうでしょうか？

I'm a rolling HomePage.  （ぼくは、転がるホームページ）
My Power is your pull request. Lets Push me.

参加者のプルリクによって、企画がどんどんあらぬ方向にゴロゴロ転がっていくみたいな面白さがあるんじゃないかと考えました。

**Comment by ookam** [comment]
おしゃれ！！🎉🎉
なんか捻ったのは面白いですよね！！

1週間くらい様子見て決めようかと思います！！他の人もアイデアあったらぜひ！！

**Comment by dowdiness** [comment]
今使われてるyaminabeは仮で付けた名前だと思いますが、サイトのやってることを直接分かりやすく表現してる気がして好きですね。

**Comment by ookam** [comment]
闇鍋になると困るんですけどたしかにちょっと面白さありますね笑

**Comment by ookam** [comment]
リポジトリ名がyaminabeなので一旦yaminabeで行きます！

良さげなのを思いついたらissueお待ちしてます！
