### ISSUE TITLE
【要望・提案】ダークモードの変更ボタンをトグル式にして使いやすくしたい！

### ISSUE THREAD

**Issue by Kissa0330** [ookam/yaminabe#50]
要望・提案の種類（一致するものを残して他は消して下さい）
- デザイン

## 私はこれを要望・提案します！
- 現状では光/闇がそれぞれ独立しているダークモードの変更ボタンの判定を一つにまとめて、一回押すたびに現状のモードとは違うモードに変更するようにして使いやすくしたい！

## サイト上でのURLやスクショ
-<img width="83" alt="スクリーンショット 2021-02-16 23 25 54" src="https://user-images.githubusercontent.com/62830507/108075986-52c20700-70ae-11eb-9ed6-08b42fd25115.png">

## 補足
-

**Comment by ookam** [comment]
めちゃ良いと思います！！！
