### ISSUE TITLE
【要望・提案】背景の闇鍋を沸騰させてほしい

### ISSUE THREAD

**Issue by hayashi-884** [ookam/yaminabe#52]
### 要望・提案の種類

- [x] デザイン
- [ ] 機能
- [ ] ドキュメント類
- [ ] 開発チーム（ここ）
- [ ] その他

### 私はこれを要望・提案します！
- トップページでダークモードにした際に背景に現れる闇鍋アイコンをアニメーションで沸騰させてください

### 補足
- 虹色がいいです

**Comment by ookam** [comment]
めっちゃ大変そう！！！！
CSSアニメーションやってる人とかいたら……！
