### ISSUE TITLE
【改善案】Issueのラベル付けやってきましょう！

### ISSUE THREAD

**Issue by mikkame** [ookam/yaminabe#61]
### 改善案の種類

- [ ] デザイン
- [ ] コード
- [ ] 技術
- [x] その他

### ここをこうしたらさらにcoolになります！
- Issueのラベル付けやってきましょう！
- コントリビューターにトリアージ権限をつけるとその辺の管理を委任できます
- ラベルは既存のやつをうまく使っていきたいですね

**Comment by noumi0k** [comment]
issueテンプレートいじって意識せずにラベル付けできるようにするのもありですかね？

**Comment by mikkame** [comment]
今選択式になってるやつはテンプレートいじって最初から乗る方がいいですね。
bug/enhanceとか。
ただ、good first issueとかhelp wantedは別途付けたくなるかな？wontfixも

**Comment by ookam** [comment]
あんまり難しい事やっても多分賢い人以外は出来ないので、1つのissueに1つのタグみたいな対応関係になるのが良さそうですね

issueテンプレをラベルの数だけ展開する方向性の方が多分良さみあります！
