### ISSUE TITLE
【改善案】GitHubのApiへのリクエストのレート制限を超えたらサイトのビルドに失敗するのを改善する

### ISSUE THREAD

**Issue by dowdiness** [ookam/yaminabe#62]
### 改善案の種類

- [ ] デザイン
- [ ] コード
- [x] 技術
- [ ] その他

### ここをこうしたらさらにcoolになります！
- 開発時には初回のリクエストをキャッシュして無駄なリクエストが飛ばないようにする？
- OAuth2 トークンを取得してみんなで使い回す？（流石に認証情報を使い回すのは問題かも？）

### coolになる度
- [x] ★ 　　| 微cool | ちょっとイケてるかも？
- [ ] ★★ 　| 中cool | そこそこイケてると思う
- [ ] ★★★ | 超cool | 絶対イケてる

### 補足
- 認証なしの状態では 1 時間あたり最大 60 件まで可能、認証ありの場合は 1 時間あたり最大 5,000 件まで可能です
https://docs.github.com/ja/rest/overview/resources-in-the-rest-api#rate-limiting

**Comment by ookam** [comment]
THX!!!🎉
