### ISSUE TITLE
【企画提案】yaminabeのコンテンツ

### ISSUE THREAD

**Issue by dtakkiy** [ookam/yaminabe#65]
### 要望・提案の種類

- [ ] デザイン
- [ ] 機能
- [ ] ドキュメント類
- [ ] 開発チーム（ここ）
- [x] その他

### 私はこれを要望・提案します！
- 追加コンテンツがほしい。

今のyaminabeは、トップページのみでちょっと寂しいので、なにか追加コンテンツがほしいと考えました。
そこで、これまでIssueなどで中二病とキーワードが上がっていたので、闇に関するコンテンツはどうでしょうか？

- 仕組み
  - ズバリ診断メーカーです。
  - テキストをインプットしたら、なにか闇のテキストが返ってくる、だけ。
  - 入れるものは、名前でもセリフでも技でも闇にかければ無限にありそう。
  - データは、最初はプレーンテキストから取得すれば十分ではないかと。

よろしければ、ご意見お聞かせ下さい。

**Comment by ookam** [comment]
簡単な診断メーカー的なやつですよね！面白そう！
ただDBを使わないとなるとデータを追加するのに毎回yml更新とかになるからそれがどうなんだろうって感じですよね！🔍🔍

**Comment by dowdiness** [comment]
もしDBを使いたいなら、AirTableを使うのはどうでしょうか？
ただ無料でどれくらい使えるのか分からないのと、githubのプルリクエストで変更出来ないとせせりさんが管理を全部しないといけないことになるので負担掛かりそうなのはどうかな？と思います。
どっちにしろDBはGithubで管理出来ないと思うので、それならこういう外部のサービスを使った方が普通にDBを使うよりかは楽だとは思います。
https://note.com/shuheikoyama/n/n63ccab24d49b
