### ISSUE TITLE
【要望・提案】マスコットキャラ欲しい

### ISSUE THREAD

**Issue by ookam** [ookam/yaminabe#8]
要望・提案の種類（一致するものを残して他は消して下さい）
- その他

## 私はこれを要望・提案します！
- 可愛いマスコットキャラを設置したい

## サイト上でのURLやスクショ
- 

## 補足
- 誰かお願いします！！

**Comment by dtakkiy** [comment]
![マスコット](https://user-images.githubusercontent.com/24822590/108005154-418be280-703b-11eb-8131-616d465a5dfc.png)
