### ISSUE TITLE
【要望・提案】おめシスさんのプルリクだけでHPを作るやつの動画貼ってほしいです！

### ISSUE THREAD

**Issue by Enya-penguin** [ookam/yaminabe#9]
要望・提案の種類（一致するものを残して他は消して下さい）

- ドキュメント類

## 私はこれを要望・提案します！
- おめシスさんの動画があると、企画の温度感が伝わりやすくていいんじゃないかなぁと思いました！
プルリク自体を知らない私のような人にとって、おめシスさんのテンションがあるだけで参加へのハードルがちょっと下がる気がします…！

## サイト上でのURLやスクショ
- 

## 補足
- サイトトップか、プルリクを送るまでのドキュメントページに貼るといいんじゃないかなと思いますが、どちらの方がいいだろう…？引きを作るにはサイトトップですが、サイトトップに動画があるサイトのデザインってお洒落にするの難しい気がするし…むむむ

**Comment by ookam** [comment]
良さそうですけど、本人達が認知してない企画なので若干勝手に貼って大丈夫かな？感はありますよね！！！大丈夫かな！！

**Comment by Enya-penguin** [comment]
た、たしかに…参考リンク程度なら許可無しでも問題無さそうですが、おもいっきりドーンと出してしまうのはちょっと微妙かもしれない…
許可さえあれば…と思いましたが取ったら取ったでオフィシャル感が出て気軽さが薄れてしまいそうだし、自分で投げといてどうなんだろうかと思えてきました…（申し訳ない）

**Comment by ookam** [comment]
とりあえず一旦保留にして、ドキュメント増えてきたらしれっと貼るイメージでいましょうか！！

今の何もないところにどーーーんと出すとイメージが強すぎますので笑

**Comment by Enya-penguin** [comment]
はいー！一旦保留でお願いします(´;ω;｀)
